export const AUDIT_ACTION = Object.freeze({
  // Auth
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',

  // User management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',

  // Wallet
  WALLET_CREDITED: 'WALLET_CREDITED',
  WALLET_DEBITED: 'WALLET_DEBITED',
  WALLET_FROZEN: 'WALLET_FROZEN',
  WALLET_UNFROZEN: 'WALLET_UNFROZEN',
  WALLET_SETTLED: 'WALLET_SETTLED',

  // Recharge
  RECHARGE_INITIATED: 'RECHARGE_INITIATED',
  RECHARGE_SUCCESS: 'RECHARGE_SUCCESS',
  RECHARGE_FAILED: 'RECHARGE_FAILED',
  RECHARGE_RETRY: 'RECHARGE_RETRY',
  RECHARGE_REFUNDED: 'RECHARGE_REFUNDED',
  RECHARGE_REVERSED: 'RECHARGE_REVERSED',

  // Settings / Config
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',

  // Operator / Plans
  OPERATOR_CREATED: 'OPERATOR_CREATED',
  OPERATOR_UPDATED: 'OPERATOR_UPDATED',
  OPERATOR_DELETED: 'OPERATOR_DELETED',
  PLAN_CREATED: 'PLAN_CREATED',
  PLAN_UPDATED: 'PLAN_UPDATED',
  PLAN_DELETED: 'PLAN_DELETED',
});

export const AUDIT_SEVERITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});
