export const TRANSACTION_STATUS = Object.freeze({
  INITIATED: 'INITIATED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  REVERSED: 'REVERSED',
  TIMEOUT: 'TIMEOUT',
});

export const TRANSACTION_TYPE = Object.freeze({
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  REFUND: 'REFUND',
  REVERSAL: 'REVERSAL',
  COMMISSION: 'COMMISSION',
  SETTLEMENT: 'SETTLEMENT',
  PENALTY: 'PENALTY',
});

export const RECHARGE_TYPE = Object.freeze({
  MOBILE_PREPAID: 'MOBILE_PREPAID',
  MOBILE_POSTPAID: 'MOBILE_POSTPAID',
});

export const TERMINAL_STATUSES = Object.freeze([
  TRANSACTION_STATUS.SUCCESS,
  TRANSACTION_STATUS.FAILED,
  TRANSACTION_STATUS.REFUNDED,
  TRANSACTION_STATUS.REVERSED,
]);

export const RETRIABLE_STATUSES = Object.freeze([
  TRANSACTION_STATUS.FAILED,
  TRANSACTION_STATUS.TIMEOUT,
]);
