export const WALLET_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
  SUSPENDED: 'SUSPENDED',
  CLOSED: 'CLOSED',
});

export const WALLET_TRANSACTION_TYPE = Object.freeze({
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  REFUND: 'REFUND',
  REVERSAL: 'REVERSAL',
  COMMISSION: 'COMMISSION',
  SETTLEMENT: 'SETTLEMENT',
  PENALTY: 'PENALTY',
  ADJUSTMENT: 'ADJUSTMENT',
});

export const WALLET_TRANSACTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
});

export const LEDGER_ENTRY_TYPE = Object.freeze({
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
});
